nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^http://localhost:[0-9]+$', '^http://127.0.0.1:[0-9]+$', '^https://localhost:[0-9]+$']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
        expose_headers: ['Link', 'X-Total-Count']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/': 
            allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173', 'https://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'Cache-Control']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 86400
            allow_credentials: true 