vich_uploader:
    db_driver: orm
    
    mappings:
        building_images:
            uri_prefix: /uploads/building
            upload_destination: '%kernel.project_dir%/public/uploads/building'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true