name: Symfony CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.3]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: citybuilder_db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql, zip
          coverage: none

      - name: Install Composer dependencies
        run: cd API && composer install --no-interaction --prefer-dist

      - name: Composer Security Audit
        run: cd API && composer audit

      - name: Copy .env.test
        run: cp API/.env.test API/.env

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            nc -z 127.0.0.1 3306 && break
            sleep 1
          done

      - name: Prepare database
        run: |
            php API/bin/console doctrine:database:drop --force --if-exists --env=test
            php API/bin/console doctrine:database:create --env=test

      - name: Run migrations
        run:  php API/bin/console doctrine:migrations:migrate --no-interaction

      - name: Run tests
        run:  php API/bin/phpunit
